// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfNKzYtV0JHxWmJHJY27Yh0xAPqFF4zM',
    appId: '1:1034358727959:android:c8b33d564b8f315fe1c352',
    messagingSenderId: '1034358727959',
    projectId: 'first-project-64aaa',
    storageBucket: 'first-project-64aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQsRSRPQ7U4DuLLryx0zpGjhbnHaM3Tq8',
    appId: '1:1034358727959:ios:df3644e18c105714e1c352',
    messagingSenderId: '1034358727959',
    projectId: 'first-project-64aaa',
    storageBucket: 'first-project-64aaa.appspot.com',
    iosClientId: '1034358727959-hrsmo7cqlc0t5ulsi3vn48v19q4a8rh7.apps.googleusercontent.com',
    iosBundleId: 'com.firebase.app',
  );
}
